import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Layout/Sidebar";
import TopBar from "@/components/Layout/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"], // Choose needed weights
  variable: "--font-poppins", // Define a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div className="flex w-full">
          <div className="w-[20%]">
            <Sidebar />
          </div>

          <div className="w-[80%] mx-auto">
            <TopBar />
            <div className="bg-[#0000000d] h-[calc(100vh-4.4rem)] w-full overflow-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
